# Generated by Django 5.2.5 on 2025-08-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('cod_clase', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cod_marca', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('cod_parte', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('cod_elemento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='inventario.clase')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='inventario.parte')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('cod_modelo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.clase')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_pieza', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.clase')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.elemento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.modelo')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.parte')),
            ],
        ),
    ]
